/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NavBar {
        /**
          * Name of the logo Used as a default placeholder if logo image is not available
         */
        "logo_name": string;
        /**
          * URL of the logo image
         */
        "logo_url": string;
    }
    interface NavBarItem {
        /**
          * Name of the nav bar item
         */
        "name": string;
        /**
          * Redirect target of the nav bar item
         */
        "target": string;
    }
}
declare global {
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLNavBarItemElement extends Components.NavBarItem, HTMLStencilElement {
    }
    var HTMLNavBarItemElement: {
        prototype: HTMLNavBarItemElement;
        new (): HTMLNavBarItemElement;
    };
    interface HTMLElementTagNameMap {
        "nav-bar": HTMLNavBarElement;
        "nav-bar-item": HTMLNavBarItemElement;
    }
}
declare namespace LocalJSX {
    interface NavBar {
        /**
          * Name of the logo Used as a default placeholder if logo image is not available
         */
        "logo_name"?: string;
        /**
          * URL of the logo image
         */
        "logo_url"?: string;
    }
    interface NavBarItem {
        /**
          * Name of the nav bar item
         */
        "name"?: string;
        /**
          * Redirect target of the nav bar item
         */
        "target"?: string;
    }
    interface IntrinsicElements {
        "nav-bar": NavBar;
        "nav-bar-item": NavBarItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "nav-bar-item": LocalJSX.NavBarItem & JSXBase.HTMLAttributes<HTMLNavBarItemElement>;
        }
    }
}
