/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NuiModal {
        /**
          * Header of the modal
         */
        "header": string;
    }
    interface NuiNavBar {
        /**
          * Name of the logo Used as a default placeholder if logo image is not available
         */
        "logo_name": string;
        /**
          * URL of the logo image
         */
        "logo_url": string;
    }
    interface NuiNavBarItem {
        /**
          * Name of the nav bar item
         */
        "name": string;
        /**
          * Link to the redirected location
         */
        "to": string;
    }
}
declare global {
    interface HTMLNuiModalElement extends Components.NuiModal, HTMLStencilElement {
    }
    var HTMLNuiModalElement: {
        prototype: HTMLNuiModalElement;
        new (): HTMLNuiModalElement;
    };
    interface HTMLNuiNavBarElement extends Components.NuiNavBar, HTMLStencilElement {
    }
    var HTMLNuiNavBarElement: {
        prototype: HTMLNuiNavBarElement;
        new (): HTMLNuiNavBarElement;
    };
    interface HTMLNuiNavBarItemElement extends Components.NuiNavBarItem, HTMLStencilElement {
    }
    var HTMLNuiNavBarItemElement: {
        prototype: HTMLNuiNavBarItemElement;
        new (): HTMLNuiNavBarItemElement;
    };
    interface HTMLElementTagNameMap {
        "nui-modal": HTMLNuiModalElement;
        "nui-nav-bar": HTMLNuiNavBarElement;
        "nui-nav-bar-item": HTMLNuiNavBarItemElement;
    }
}
declare namespace LocalJSX {
    interface NuiModal {
        /**
          * Header of the modal
         */
        "header"?: string;
    }
    interface NuiNavBar {
        /**
          * Name of the logo Used as a default placeholder if logo image is not available
         */
        "logo_name"?: string;
        /**
          * URL of the logo image
         */
        "logo_url"?: string;
    }
    interface NuiNavBarItem {
        /**
          * Name of the nav bar item
         */
        "name"?: string;
        /**
          * Link to the redirected location
         */
        "to"?: string;
    }
    interface IntrinsicElements {
        "nui-modal": NuiModal;
        "nui-nav-bar": NuiNavBar;
        "nui-nav-bar-item": NuiNavBarItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nui-modal": LocalJSX.NuiModal & JSXBase.HTMLAttributes<HTMLNuiModalElement>;
            "nui-nav-bar": LocalJSX.NuiNavBar & JSXBase.HTMLAttributes<HTMLNuiNavBarElement>;
            "nui-nav-bar-item": LocalJSX.NuiNavBarItem & JSXBase.HTMLAttributes<HTMLNuiNavBarItemElement>;
        }
    }
}
