/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NavBar {
        /**
          * Name of the logo Used as a default placeholder if logo image is not available
         */
        "logo_name": string;
        /**
          * URL of the logo image
         */
        "logo_url": string;
        /**
          * Navigation items
         */
        "nav_items": string[];
    }
}
declare global {
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "nav-bar": HTMLNavBarElement;
    }
}
declare namespace LocalJSX {
    interface NavBar {
        /**
          * Name of the logo Used as a default placeholder if logo image is not available
         */
        "logo_name"?: string;
        /**
          * URL of the logo image
         */
        "logo_url"?: string;
        /**
          * Navigation items
         */
        "nav_items"?: string[];
    }
    interface IntrinsicElements {
        "nav-bar": NavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
        }
    }
}
